// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9vL0CsTrQcmksNe7JDhBf4_06D6KsEk',
    appId: '1:333895864153:web:ddbb246a07ab0a67bb8648',
    messagingSenderId: '333895864153',
    projectId: 'tourmate-bd9e8',
    authDomain: 'tourmate-bd9e8.firebaseapp.com',
    databaseURL: 'https://tourmate-bd9e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tourmate-bd9e8.firebasestorage.app',
    measurementId: 'G-BWKYF8VL8C',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs9vL0CsTrQcmksNe7JDhBf4_06D6KsEk',
    appId: '1:333895864153:web:6e8aa954828938e8bb8648',
    messagingSenderId: '333895864153',
    projectId: 'tourmate-bd9e8',
    authDomain: 'tourmate-bd9e8.firebaseapp.com',
    databaseURL: 'https://tourmate-bd9e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tourmate-bd9e8.firebasestorage.app',
    measurementId: 'G-BTBJYMQ2LG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1KSwSc5soaDrvte2RyaELBt9_CumwjY',
    appId: '1:333895864153:ios:f688fa18e260e223bb8648',
    messagingSenderId: '333895864153',
    projectId: 'tourmate-bd9e8',
    databaseURL: 'https://tourmate-bd9e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tourmate-bd9e8.firebasestorage.app',
    iosClientId: '333895864153-9f2hromj2pvl2ohoahafk9214f68dk5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourmateApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_WWSTXU_oXIIaCxbdHmvOMShvrsS3lE',
    appId: '1:333895864153:android:4c595e9b80321a49bb8648',
    messagingSenderId: '333895864153',
    projectId: 'tourmate-bd9e8',
    databaseURL: 'https://tourmate-bd9e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tourmate-bd9e8.firebasestorage.app',
  );

}