import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // ✅ Import the generated file
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:tourmate_app/l10n/app_localizations.dart';
import 'package:tourmate_app/screens/root_screen.dart';
import 'package:tourmate_app/screens/app_preview_screen.dart';
import 'package:tourmate_app/services/tour_reminder_service.dart';
import 'package:tourmate_app/providers/language_provider.dart';
import 'utils/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Initialize Firebase with the default options generated by flutterfire configure
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("Firebase initialized successfully!");

    try {
      await FirebaseFirestore.instance.collection('debug').doc('ping').get();
      debugPrint("Firestore reachable ✅");
    } catch (e) {
      debugPrint("Firestore connection failed ❌: $e");
    }
  } catch (e) {
    print("Error initializing Firebase: $e");
    // Handle the error appropriately, perhaps by showing an error screen
  }

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize tour reminder service
  final tourReminderService = TourReminderService();
  tourReminderService.startReminderService();

  // Initialize language provider
  final languageProvider = LanguageProvider();
  await languageProvider.loadAppLanguage();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => languageProvider),
      ],
      child: const TourMateApp(),
    ),
  );
}

class TourMateApp extends StatelessWidget {
  const TourMateApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<LanguageProvider>(
      builder: (context, languageProvider, child) {
        return MaterialApp(
          title: 'TourMate',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.lightTheme,
          locale: languageProvider.currentLocale,
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: AppLocalizations.supportedLocales,
          home: const AppPreviewScreen(),
        );
      },
    );
  }
}
